### ISSUE TITLE
IncreaseBrush/DecreaseBrush inversion in Geared version

### ISSUE THREAD

**Issue by klem0810** [beto-rodriguez/Live-Charts#476]
By replacing CandleSeries by GCandleSeries, you should see an inversion of the colors. It seems that IncreaseBrush and DecreaseBrush properties are inverted in code.

**Comment by beto-rodriguez** [comment]
Thank you ver much for the report, I am finally building an example with financial series using the geared package, and it will be in the site soon, I have noticed many issues with this series, I am fixing them as I am building the article.

I am closing this issue, it is already solved and will be included in the next version of the geared package 1.2.6

**Comment by klem0810** [comment]
Hi Beto, I just noticed that the problem is still there.


Live-Charts version | 1.2.9 (Geared)
-- | --
.Net Version | 4.6.1
Windows | Win10 Home

**Comment by klausbyskov** [comment]
The brushes are not inverted. It is notion of `increase` vs. `decrease` that are in fact reversed. A point where `Open > Close` uses the `IncreaseBrush` and a point where `Close > Open` uses the `DecreaseBrush`, which should be the other way round. It would be nice if you could fix it @beto-rodriguez , but the workaround is to just assign the brushes in Xaml keeping in mind that the `IncreaseBrush` is used for decreasing candles, and vice versa.
