### ISSUE TITLE
Series.Clear(); Doesnt Clear Series

### ISSUE THREAD

**Issue by b1u3w01f** [beto-rodriguez/Live-Charts#76]
Trying a little rework to the workaround in #74 and Series.Clear() (The SeriesCollection) doesn't seem to clear. Result is a very weird graph output below with each Collection read being plotted and then remaining 'in the background'.

![refreshpng](https://cloud.githubusercontent.com/assets/13273975/12517844/e5a3bad2-c12c-11e5-977a-a200161aff95.PNG)

**Comment by beto-rodriguez** [comment]
this is sadly not supported for observable collections http://stackoverflow.com/questions/224155/when-clearing-an-observablecollection-there-are-no-items-in-e-olditems any suggestions?

**Comment by beto-rodriguez** [comment]
Actually we can fix this with something like:

```c#
if (e.Action == Specialized.NotifyCollectionChangedAction.Reset) 
//then remove all series from chart
```

will fix as soon as possible

**Comment by beto-rodriguez** [comment]
@b1u3w01f Thanks for reporting, this examples shows the fix https://github.com/beto-rodriguez/Live-Charts/tree/master/ChartsTest/BarExamples/Mvvm

**Comment by serekmt2** [comment]
Hi, I have an issue with LineChart. the chart is crashing when i'm emptying  SeriesCollection or any of values in ChartValues is empty. I case of SeriesCollection it's throwing ArgumentException while with ChartValues throws a NullReferenceException


The same thing is happening in that example above so I thought it's a good place to write about it. When i click a clear button it crash with ArgumentException as followed: 

ArgumentException while with 

"An unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll
Additional information: 'not a number' is not a valid value for property 'Y1'."

**Comment by beto-rodriguez** [comment]
@serekmt2 Thanks for reporting, will test and fix as soon as possible, also finally I will add Unit Testing to this project since this is a common bug when we deploy a new release

**Comment by beto-rodriguez** [comment]
@serekmt2 you are using 0.6.1 right?

**Comment by serekmt2** [comment]
It was on 0.6.0 is it fixed in 0.6.1?

**Comment by beto-rodriguez** [comment]
this issue was solved in 0.6.1 https://github.com/beto-rodriguez/Live-Charts/releases/tag/0.6.1

**Comment by serekmt2** [comment]
Thx for the information. Gonna go to 0.6.0 but i have to change all the namespaces.

**Comment by beto-rodriguez** [comment]
@serekmt2 I am sorry about changing namespace too often, It wont happen again

**Comment by truten** [comment]
Hi,
Sorry to reopen an old issues but I'm having the same problem as  b1u3w01f.
After drawing a cartesianchart i clean it by calling:
cartesianchart.series.clear()
cartesianchart.axisy.clear()
cartesianchart.axisx.clear()

But the result still have some dots in of the previous series.
I have read the discussion but I don't understand the solution made by beto-rodriguez.
Any help?

Many thanks.

**Comment by mcanyucel** [comment]
I also have the same issue; even though I call `viewModel.chartValues.clear()` where `chartValues` is of type `ChartValues<T>`, the next time I start populating the same chart, phantom points appear. Moreover, I tried assigning a new instance to a chart but still the issue remains. The effect may be seen in the following GIF:
![livecharts](https://cloud.githubusercontent.com/assets/3370883/25989804/38083e6a-3706-11e7-9fbf-3a54e7df2246.gif)

**Comment by beto-rodriguez** [comment]
I reopened this issue, thanks both for the feedback, could you please share a small snippet so I can reproduce easier?

Thanks

**Comment by buybackoff** [comment]
I am having the same issue with artifacts and random straight lines on my real-time charts, similar to the picture above by mcanyucel, but I do not call .Clear() on series but rather replace them completely with new ones. If I call clear then there is a total mess as if the old points are not deleted at all.

The straight lines appear not always, but randomly, probably some syncronization issue. Will post gif/code later. My point is that not only Clear() causes artifacts...

**Comment by Rodbourn** [comment]
Same issue here.

**Comment by truten** [comment]
Hi,

Totally forgot about this since I was very busy.
If the snippet could still be usefull I will try to provide it in the week.

Bye and thanks

**Comment by Tam66662** [comment]
Also having this issue.  No matter what I do to clear the Values from my LineSeries, there is still some visual trace of random points that affect the drawing.

I've tried:
 Clear on my ChartValues<T> 

- Clear() on my ChartValues<T> collection
- Clean() on my AxisX/AxisY 
- Clear() on the Series of my CartesianChart, then completely resetting the CartesianChart's LineSeries in code-behind

Whenever I start adding values back into my ChartValues<T> collection, there are errant visual traces of lines across my line graph.

It should look like this:
![image](https://user-images.githubusercontent.com/12551526/41751012-e869ecb6-7573-11e8-89f0-b47697ee9f14.png)


Instead it looks like this after I re-run a cleaned chart:
![image](https://user-images.githubusercontent.com/12551526/41751033-03480f4a-7574-11e8-96a1-d70329514d06.png)

Thanks

**Comment by Shadowmafia** [comment]
Clear Points : https://github.com/Shadowmafia/First-MultiThreading-HomeWork-C-WPF-Graphs
In this project, in the OutputDiagram window ->RefreshChart ().

**Comment by Danarrow** [comment]
Hello, 

i have the same issue like "truten".
Is there already a solution to this problem?

Regards

**Comment by truten** [comment]
Hello,

It has passed quite some time and I don't recall very well but I think that I mitigated the problem by completely removing the  points.

line_t1.PointGeometrySize = 0 before adding the series graph.Series.Add(line_t1).

Hope it helps.

**Comment by Danarrow** [comment]
Hello,

thank you for the fast answer.
The problem with the dots is now solved by deactivating them. 
Nevertheless, sometimes unwanted side effects still occur when lines are changed or newly created. 
Then it looks almost like mcanyucel's gif.

Is there already a solution or patch for this issue?

Regards

**Comment by prebusmaximus** [comment]
This is still not fixed. I find the lack of interest in fixing this amazing.......

I even do the following in order to try;
```csharp
chartConsumption.Series[0].ActualValues.Clear();
chartConsumption.Series[0].Values.Clear();
chartConsumption.Series.Clear();
chartConsumption.AxisX.Clear();
chartConsumption.AxisY.Clear();					
chartConsumption.Update(true, true);
chartConsumption.PerformLayout();
```

![image](https://user-images.githubusercontent.com/23620120/112005636-3db01c00-8b23-11eb-81e3-db327bc5bdee.png)

**Comment by truten** [comment]
Hello,

Unfortunately this library hasn't been updated in a few years so I think you have two possibilities at the moment:

- use the workaround (disable points)
- change library

Beto, the creator, was working on a V2 so maybe in the future the situation will change: I hope it since I like this library.

**Comment by prebusmaximus** [comment]
> Hello,
> 
> Unfortunately this library hasn't been updated in a few years so I think you have two possibilities at the moment:
> 
> * use the workaround (disable points)
> * change library
> 
> Beto, the creator, was working on a V2 so maybe in the future the situation will change: I hope it since I like this library.

Ok, thank you for the answer. I will look for another control library to use then.... shame, this one was really nice :-)

**Comment by beto-rodriguez** [comment]
@prebusmaximus sorry for that, v0 (this repo) is much harder to maintain.

the new version https://github.com/beto-rodriguez/LiveCharts2 introduces many interesting features, it is much easier to maintain, is much more solid,  I hope we can have the first Nuget package in 15 days - 1 month.

**Comment by wasilus** [comment]
I could find no documentation on how to use LiveCharts2 with WPF.
